version: '3.3'
services:
  main:
    container_name: main
    build:
     context: .
    volumes:
      - ./usr/app
      - ./usr/app/node_modules
    ports:
      - 8081:8081
    command:
        - yarn
        - yarn server:dev
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
        image: 'mysql:latest'
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db
        restart: always
        ports:
        - '3306:3306'
        hostname: 127.0.0.1
        volumes:
        - ./db:/bitnami/mysql/data
